# Generated by Django 6.0.3 on 2026-03-31 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres.')])),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'La descripción debe ser más detallada (mínimo 10 caracteres).')])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'El precio debe ser mayor a 0.')])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'El stock no puede ser negativo.')])),
                ('categoria', models.CharField(choices=[('Notebooks', 'Notebooks'), ('Smartphones', 'Smartphones'), ('Tablets', 'Tablets'), ('Accesorios', 'Accesorios')], max_length=50)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen del producto', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
